# ~/.config/fish/completions/scrcpy.fish

# 如果scrcpy命令不存在，则不加载此补全脚本
if not type -q scrcpy
    return
end

# 帮助选项
complete -c scrcpy -s h -l help -d "打印此帮助信息。"
complete -c scrcpy -s v -l version -d "打印scrcpy的版本。"

# 无参数选项 (flags)
complete -c scrcpy -l always-on-top -d "使scrcpy窗口始终置于其他窗口之上。"
complete -c scrcpy -l audio-dup -d "复制音频（捕获并继续在设备上播放）。"
complete -c scrcpy -l camera-high-speed -d "启用高速相机捕获模式。"
complete -c scrcpy -l disable-screensaver -d "在scrcpy运行时禁用屏幕保护程序。"
complete -c scrcpy -s f -l fullscreen -d "以全屏模式启动。"
complete -c scrcpy -l force-adb-forward -d "不尝试使用\"adb reverse\"连接到设备。"
complete -c scrcpy -s G -d "与--gamepad=uhid相同，如果设置了--otg则为--gamepad=aoa。"
complete -c scrcpy -s K -d "与--keyboard=uhid相同，如果设置了--otg则为--keyboard=aoa。"
complete -c scrcpy -l kill-adb-on-close -d "scrcpy终止时终止adb。"
complete -c scrcpy -l legacy-paste -d "将计算机剪贴板文本作为一系列按键事件注入（类似MOD+Shift+v）。"
complete -c scrcpy -l list-apps -d "列出设备上安装的Android应用。"
complete -c scrcpy -l list-cameras -d "列出设备相机。"
complete -c scrcpy -l list-camera-sizes -d "列出有效的相机捕获尺寸。"
complete -c scrcpy -l list-displays -d "列出设备显示器。"
complete -c scrcpy -l list-encoders -d "列出设备上可用的视频和音频编码器。"
complete -c scrcpy -s M -d "与--mouse=uhid相同，如果设置了--otg则为--mouse=aoa。"
complete -c scrcpy -s n -l no-control -d "禁用设备控制（只读镜像设备）。"
complete -c scrcpy -s N -l no-playback -d "禁用计算机上的视频和音频播放。"
complete -c scrcpy -l no-audio -d "禁用音频转发。"
complete -c scrcpy -l no-audio-playback -d "禁用计算机上的音频播放。"
complete -c scrcpy -l no-cleanup -d "默认情况下，scrcpy会在退出时移除设备上的服务器二进制文件并恢复设备状态。此选项禁用此清理功能。"
complete -c scrcpy -l no-clipboard-autosync -d "禁用剪贴板的自动同步。"
complete -c scrcpy -l no-downsize-on-error -d "默认情况下，MediaCodec错误时，scrcpy会自动尝试使用较低的分辨率。此选项禁用此行为。"
complete -c scrcpy -l no-key-repeat -d "当按键按住时，不转发重复的按键事件。"
complete -c scrcpy -l no-mipmaps -d "禁用mipmaps的生成。"
complete -c scrcpy -l no-mouse-hover -d "不转发鼠标悬停（无任何点击的鼠标移动）事件。"
complete -c scrcpy -l no-power-on -d "启动时不开启设备电源。"
complete -c scrcpy -l no-vd-destroy-content -d "禁用虚拟显示器“移除时销毁内容”标志。"
complete -c scrcpy -l no-vd-system-decorations -d "禁用虚拟显示器系统装饰标志。"
complete -c scrcpy -l no-video -d "禁用视频转发。"
complete -c scrcpy -l no-video-playback -d "禁用计算机上的视频播放。"
complete -c scrcpy -l no-window -d "禁用scrcpy窗口。"
complete -c scrcpy -l otg -d "在OTG模式下运行：模拟物理键盘和鼠标。"
complete -c scrcpy -l power-off-on-close -d "关闭scrcpy时关闭设备屏幕。"
complete -c scrcpy -l prefer-text -d "将字母字符和空格作为文本事件而非按键事件注入。"
complete -c scrcpy -l print-fps -d "启动FPS计数器，将帧率日志打印到控制台。"
complete -c scrcpy -l raw-key-events -d "注入所有输入键的按键事件，并忽略文本事件。"
complete -c scrcpy -l require-audio -d "默认情况下，当设备上的音频捕获失败时，scrcpy只镜像视频。此选项使scrcpy在音频启用但不起作用时失败。"
complete -c scrcpy -s S -l turn-screen-off -d "立即关闭设备屏幕。"
complete -c scrcpy -s t -l show-touches -d "启动时启用“显示触摸”，退出时恢复初始值。"
complete -c scrcpy -s w -l stay-awake -d "在scrcpy运行时，当设备插入电源时，保持设备开启。"
complete -c scrcpy -l window-borderless -d "禁用窗口装饰（显示无边框窗口）。"

# 带有参数的选项
complete -c scrcpy -l angle -r -d "以自定义角度（顺时针）旋转视频内容，单位为度。"
complete -c scrcpy -l audio-bit-rate -r -d "以给定比特率编码音频，单位为bits/s。"
complete -c scrcpy -l audio-buffer -r -d "配置音频缓冲延迟（毫秒）。"
complete -c scrcpy -l audio-encoder -r -d "使用特定的MediaCodec音频编码器。"
complete -c scrcpy -l audio-output-buffer -r -d "配置SDL音频输出缓冲区的大小（毫秒）。"
complete -c scrcpy -s b -l video-bit-rate -r -d "以给定比特率编码视频，单位为bits/s。"
complete -c scrcpy -l camera-fps -r -d "指定相机捕获帧率。"
complete -c scrcpy -l camera-id -r -d "指定要镜像的设备相机ID。"
complete -c scrcpy -l display-id -r -d "指定要镜像的设备显示ID。"
complete -c scrcpy -s m -l max-size -r -d "将视频的宽度和高度都限制为给定值。"
complete -c scrcpy -l max-fps -r -d "限制屏幕捕获的帧率。"
complete -c scrcpy -s p -l port -r -d "设置客户端用于监听的TCP端口（范围）。"
complete -c scrcpy -l screen-off-timeout -r -d "设置scrcpy运行时屏幕关闭超时。"
    # --- 这里是针对 -s/--serial 参数的修改 ---
complete -c scrcpy -s s -l serial -f -ra "(adb devices | tail -n +2 | awk '{print \$1}')" -d "设备序列号。当多个设备连接到adb时强制使用。"
complete -c scrcpy -l time-limit -r -d "设置最大镜像时间，单位为秒。"
complete -c scrcpy -l tunnel-host -r -d "设置adb隧道的IP地址以到达scrcpy服务器。"
complete -c scrcpy -l tunnel-port -r -d "设置adb隧道的TCP端口以到达scrcpy服务器。"
complete -c scrcpy -l v4l2-buffer -r -d "在推送帧之前添加缓冲延迟（毫秒）。"
complete -c scrcpy -l video-buffer -r -d "在显示视频帧之前添加缓冲延迟（毫秒）。"
complete -c scrcpy -l video-encoder -r -d "使用特定的MediaCodec视频编码器。"
complete -c scrcpy -l window-title -r -d "设置自定义窗口标题。"
complete -c scrcpy -l window-x -r -d "设置初始窗口水平位置。默认值为\"auto\"。"
complete -c scrcpy -l window-y -r -d "设置初始窗口垂直位置。默认值为\"auto\"。"
complete -c scrcpy -l window-width -r -d "设置初始窗口宽度。"
complete -c scrcpy -l window-height -r -d "设置初始窗口高度。"
complete -c scrcpy -s V -l verbosity -f -a "verbose debug info warn error" -d "设置日志级别。"

# 带有预定义参数值的选项
complete -c scrcpy -l audio-codec -f -a "opus aac flac raw" -d "选择音频编解码器。"
complete -c scrcpy -l audio-source -f -a "output playback mic mic-unprocessed mic-camcorder mic-voice-recognition mic-voice-communication voice-call voice-call-uplink voice-call-downlink voice-performance" -d "选择音频源。"
complete -c scrcpy -l camera-ar -f -a "sensor 4:3 16:9 1.6 1.77 21:9" -d "按宽高比选择相机尺寸（例如\"sensor\", \"4:3\", \"1.6\"）。"
complete -c scrcpy -l camera-facing -f -a "front back external" -d "按朝向选择设备相机。"
complete -c scrcpy -l capture-orientation -f -a "0 90 180 270 flip0 flip90 flip180 flip270 @0 @90 @180 @270 @" -d "设置捕获视频方向。"
complete -c scrcpy -l display-ime-policy -f -a "local fallback hide" -d "设置IME应显示在哪里的策略。"
complete -c scrcpy -l display-orientation -f -a "0 90 180 270 flip0 flip90 flip180 flip270" -d "设置初始显示方向。"
complete -c scrcpy -l gamepad -f -a "disabled uhid aoa" -d "选择如何向设备发送游戏手柄输入。"
complete -c scrcpy -l keyboard -f -a "disabled sdk uhid aoa" -d "选择如何向设备发送键盘输入。"
complete -c scrcpy -l mouse -f -a "disabled sdk uhid aoa" -d "选择如何向设备发送鼠标输入。"
complete -c scrcpy -l orientation -f -a "0 90 180 270 flip0 flip90 flip180 flip270" -d "设置显示和录制方向。"
complete -c scrcpy -l pause-on-exit -f -a "true false if-error" -d "配置退出时暂停。传递此选项无参数等同于传递\"true\"。"
complete -c scrcpy -l record-format -f -a "mp4 mkv m4a mka opus aac flac wav" -d "强制录制格式。"
complete -c scrcpy -l record-orientation -f -a "0 90 180 270" -d "设置录制方向。"
complete -c scrcpy -l render-driver -f -a "direct3d opengl opengles2 opengles metal software" -d "请求SDL使用给定的渲染驱动程序。"
complete -c scrcpy -l shortcut-mod -f -a "lctrl rctrl lalt ralt lsuper rsuper" -d "指定scrcpy快捷键的修饰符（如\"lctrl,lsuper\"）。"
complete -c scrcpy -l video-codec -f -a "h264 h265 av1" -d "选择视频编解码器。"
complete -c scrcpy -l video-source -f -a "display camera" -d "选择视频源。"

# 带有文件/目录路径参数的选项
complete -c scrcpy -l push-target -r -f -a "( __fish_complete_directories )" -d "设置通过拖放推送文件到设备的目录。"
complete -c scrcpy -s r -l record -r -f -a "( __fish_complete_path )" -d "将屏幕录制到文件。"
complete -c scrcpy -l v4l2-sink -r -f -a "( __fish_complete_path )" -d "输出到v4l2loopback设备。此功能仅适用于Linux。"

# 带有复杂参数格式的选项
complete -c scrcpy -l audio-codec-options -r -d "为设备音频编码器设置逗号分隔的键值对选项（例如key:type=value）。"
complete -c scrcpy -l camera-size -r -d "指定显式相机捕获尺寸（例如1920x1080）。"
complete -c scrcpy -l crop -r -d "在服务器上裁剪设备屏幕（例如width:height:x:y）。"
complete -c scrcpy -l mouse-bind -r -d "配置辅助点击的绑定（例如xxxx:xxxx）。"
complete -c scrcpy -l new-display -r -d "创建具有指定分辨率和密度的虚拟显示器（例如--new-display=1920x1080/420）。"
complete -c scrcpy -l start-app -r -d "通过其精确包名启动Android应用（例如--start-app=?firefox）。"
complete -c scrcpy -l tcpip -r -d "通过TCP/IP配置并连接设备（例如--tcpip=192.168.1.1:5555）。"

# 互斥选项
complete -c scrcpy -s d -l select-usb -x -a "-e --select-tcpip" -d "使用USB设备（如果只有一个）。"
complete -c scrcpy -s e -l select-tcpip -x -a "-d --select-usb" -d "使用TCP/IP设备（如果只有一个）。"

